### ISSUE TITLE
关于用AWR2243+DCA1000解析数据格式的问题

### ISSUE THREAD

**Issue by Kohaneee** [gaoweifan/pyRadar#11]
在距离-多普勒或者在距离-角度图中，多普勒和角度的表示都是用bins表示，能否像距离一样转换成相应的m/s或者°呢？如果是像距离一样根据分辨率来画图，那么我的多普勒和角度分辨率又如何获取呢？
![%N$6H~S47HQ(HP}I6 %X18C](https://github.com/gaoweifan/pyRadar/assets/143087521/ddcb62cc-2089-469e-b47d-23848db64185)

**Comment by gaoweifan** [comment]
可以的，算出速度/角度分辨率再乘上去就能得到速度/角度了，可以参考matlab示例代码[testDecodeADCdata.mlx](/gaoweifan/pyRadar/blob/main/matlabExample/testDecodeADCdata.mlx)。至于角度估计会复杂一些，直接FFT出来的角度精度不高，可以用一些波束成型的算法来提高角度分辨率。

**Comment by Kohaneee** [comment]
好的明白了，感谢回复
