### ISSUE TITLE
关于用AWR2243+DCA1000获取3D点云的问题

### ISSUE THREAD

**Issue by Kohaneee** [gaoweifan/pyRadar#12]
您好，我在实践中发现，数据后处理的代码中只包含距离-速度，距离-角度等二维信息，请问在您的代码中有得到3D点云的部分吗？或者您知道在TI的项目中如何得到像studio中的点云吗？

**Comment by gaoweifan** [comment]
在这个项目中我好像没有详细写获取点云相关的示例，但有提供gtrack，通过点云得到目标轨迹。不过点云的获取其实很简单，简单来说就是找峰值。比如要想从range-fft得到纵向距离维度上的目标点，可以设定一个阈值，超过该阈值的距离bin判定为峰值（目标），所有峰值处距离bin的点的集合，就是纵向距离维度的一维点云。而如果把多天线考虑进去，得到横向的azimuth-fft，选取一定阈值，超过该阈值判定为目标，即可得到角度维度的点云集合，转换成直角坐标系，就得到了二维xy的点云集合，同理对doppler-fft做类似操作就可以得到速度信息。而取阈值的方法有很多，常见的是CFAR，可以保证阈值随噪声起伏，减小噪声干扰。为了加速运算通常会先对range-fft做cfar，得到目标距离维信息，对该距离单独做doppler-fft，而不必对所有距离全都做一遍。另外，角度信息的获取也有更多的方法，比如波束成型之类的算法，不一定是简单的fft，可以得到分辨率更高的结果。还可利用DBSCAN之类的方法将点聚类，区分每个点属于哪个目标。

**Comment by Kohaneee** [comment]
了解了，谢谢您
