### ISSUE TITLE
安装fpga_udp时出了问题

### ISSUE THREAD

**Issue by Nick-Sun1018** [gaoweifan/pyRadar#14]
报错信息：/home/bit/anaconda3/envs/pytorch/compiler_compat/ld: cannot find -lftd2xx: 没有那个文件或目录，请问如何解决
![2024-05-11 17-21-29 的屏幕截图](https://github.com/gaoweifan/pyRadar/assets/61535862/35de251d-d293-4349-80f2-6352ceea5fe7)

**Comment by Nick-Sun1018** [comment]
![Uploading 2024-05-11 17-21-29 的屏幕截图.png…]()

**Comment by Nick-Sun1018** [comment]
![2024-05-11 17-21-29 的屏幕截图](https://github.com/gaoweifan/pyRadar/assets/61535862/7f0e2f31-e182-4871-b46c-4b8cb3378541)

**Comment by gaoweifan** [comment]
需要安装FTDI D2XX驱动，参见自述文件Prerequisites->Software->Linux下的说明

**Comment by Nick-Sun1018** [comment]
感谢您的回复，我重新检查了一下，我的电脑上安装路径应该在/usr/lib，加上了链接就解决了
