### ISSUE TITLE
安装fpga_udp后执行import显示ImportError: DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by swx1997** [gaoweifan/pyRadar#4]
![image](https://github.com/gaoweifan/pyRadar/assets/81855679/227e5c66-afa3-4faa-828e-004311ce0e8e)

明明有但是显示第一行就出错，感觉是打包的问题，请问怎么解决啊

**Comment by gaoweifan** [comment]
之前有个人用conda虚拟环境也出现过类似问题，我只在不用虚拟环境的原生python环境下测试过，你可以试试不启动conda虚拟环境直接在命令行用python安装Sent from my iPhoneOn Jul 24, 2023, at 11:54 AM, swx1997 ***@***.***> wrote:﻿

明明有但是显示第一行就出错，感觉是打包的问题，请问怎么解决啊

**Comment by HarperHao** [comment]
> 

您好，请问您解决了吗？我也遇到了同样的问题

**Comment by gaoweifan** [comment]
问题找到了，这个是找不到ftd2xx.dll导致的。请根据readme说明下载FTDI D2XX驱动，并将驱动的amd64目录下的ftd2xx64.dll复制到C:\Windows\System32并重命名为ftd2xx.dll。若为32位系统则将i386目录下的ftd2xx.dll复制过去即可。 @HarperHao @wantine

**Comment by HarperHao** [comment]
多谢作者，解决了
