### ISSUE TITLE
IWR 1843 实时采集并处理数据

### ISSUE THREAD

**Issue by wantine** [gaoweifan/pyRadar#5]
您好，您的代码中realtime proc 是针对AWR2243的，我想请问这个代码可以用于IWR1843的实时采集及处理吗？如果可以的话，哪些改变是关键的？非常感谢。

**Comment by gaoweifan** [comment]
完全可以，请参考这个[issue](3#issuecomment-1632803528)里的代码。重启、配置文件等初始代码不变，后面的需要变更为该issue给出的示例代码。
