### ISSUE TITLE
module 'fpga_udp' has no attribute 'radar_start_read_thread'

### ISSUE THREAD

**Issue by fiala10** [gaoweifan/pyRadar#6]
Hi, 
I would like to use your code for my laboratory test, but I am stuck on this error.

module 'fpga_udp' has no attribute 'radar_start_read_thread'

Do you have any ideas on how to solve this issue?

Thanks a lot. 

Martin

![error](https://github.com/gaoweifan/pyRadar/assets/140416294/c573a3f5-ede0-4c64-a4bc-24e7b8a7189f)

**Comment by gaoweifan** [comment]
Have you installed 'fpga_udp' module as required? Check if you did by running `pip show --files fpga_udp`.

**Comment by fiala10** [comment]
Thank you, now it is working. However, I stucked again, when i start command python captureAll.py

I got his message...FPGA Version : 2.8 [Record]
Config fpga: success
Config record packet delay: success
press ENTER to start capture...
data reading process started
Start streaming
**>>> sensorStart
b''
min Packet Num: 676**

**Comment by gaoweifan** [comment]
This issue has been raised before, please refer to #2 for more information, especially try switching to ["Method 2"](https://github.com/gaoweifan/pyRadar/issues/2#issuecomment-1564261036).

**Comment by fiala10** [comment]
Thank you very much. Otherwise, do you have any idea, why I had recieved empty file? 
![image](https://github.com/gaoweifan/pyRadar/assets/140416294/badacbcf-c110-4894-871b-158cb0e0085c)

**Comment by gaoweifan** [comment]
Have you tried [mmWave_Demo_Visualizer](https://dev.ti.com/gallery/view/mmwave/mmWave_Demo_Visualizer/ver/3.6.0/)? if the mmWave_Demo_Visualizer can run successfully, the configuration file should work fine in this program as well.

**Comment by fiala10** [comment]
No, I have problem with connection DATA_OUTPUT_PORT. Do you think, that it would be problem in my drivers? 
![image](https://github.com/gaoweifan/pyRadar/assets/140416294/e666a88b-6aee-4f7e-baaa-454ad598e1e9)
![image](https://github.com/gaoweifan/pyRadar/assets/140416294/d82e7db8-11c9-4e76-af08-5e0d6870c259)

**Comment by gaoweifan** [comment]
What version of firmware are you using? I think  it is more likely that you’re using a firmware without UART data output feature. Pls install the firmware called “xwr18xx_mmw_demo” by following [mmwaveSDK](https://www.ti.com/tool/MMWAVE-SDK) user guide.
