### ISSUE TITLE
All capture result values are zero.

### ISSUE THREAD

**Issue by pmankyu** [gaoweifan/pyRadar#9]
I'm testing with AWR2243 with DCA1000, in the order shown on README.md .

It said successful without error, but when I tried testDecode_AWR2243, all 0s were output.
I found out about it was
"Interpreting a Single Frame - Range" shows the following error.

/tmp/ipykernel_6855/3350058675.py:13: RuntimeWarning: divide by zero encountered in log
plt.imshow(np.log(np.abs(range_plot[:,0,:,:].sum(1)).T))T))

I want to solve it. What should I do? Help me

**Comment by gaoweifan** [comment]
Make sure you have a valid configuration profile, and placed a reflector in front of the antenna array. You can try [mmwaveStudio](https://www.ti.com/tool/MMWAVE-STUDIO) first, then [mmWave-DFP-2G](https://www.ti.com/tool/MMWAVE-DFP),  to verify your parameters. btw, the reason why "RuntimeWarning: divide by zero encountered in log" occurred is that your input is all zeros.

**Comment by gaoweifan** [comment]
Make sure you have a valid configuration profile, and placed a reflector in front of the antenna array. You can try [mmwaveStudio](https://www.ti.com/tool/MMWAVE-STUDIO) first, then [mmWave-DFP-2G](https://www.ti.com/tool/MMWAVE-DFP),  to verify your parameters. btw, the reason why "RuntimeWarning: divide by zero encountered in log" occurred is that your input is all zeros.
